ep3/config/routes.rb
Rails.application.routes.draw do
  get 'control_users/index'
  devise_for :users
  get 'welcome/index'

  root 'welcome#index'

  resources :games
  resources :developers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ep3/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ep3/app/models/developer.rb
class Developer < ApplicationRecord
  has_many :games

  validates :name, presence: true

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "50x50>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

end

ep3/app/models/game.rb
class Game < ApplicationRecord
  belongs_to :developer

  validates :name, :genre, :description, :release , presence: true

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "50x50>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/


end

ep3/app/models/user.rb
class User < ApplicationRecord

  enum role: [:normal_user, :admin]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

ep3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include Pundit

  protect_from_forgery

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  private
    def user_not_authorized
      flash[:notice] = "Restricted area!"
      redirect_to(request.referrer || root_path)
    end
end

ep3/app/controllers/control_users_controller.rb
class ControlUsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    authorize @users
  end
end

ep3/app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  before_action :set_developer, only: [:show, :edit, :update, :destroy]

  # GET /developers
  # GET /developers.json
  def index
    @developers = Developer.all
  end

  # GET /developers/1
  # GET /developers/1.json
  def show
  end

  # GET /developers/new
  def new
    @developer = Developer.new
  end

  # GET /developers/1/edit
  def edit
  end

  # POST /developers
  # POST /developers.json
  def create
    @developer = Developer.new(developer_params)

    respond_to do |format|
      if @developer.save
        format.html { redirect_to @developer, notice: 'Developer was successfully created.' }
        format.json { render :show, status: :created, location: @developer }
      else
        format.html { render :new }
        format.json { render json: @developer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /developers/1
  # PATCH/PUT /developers/1.json
  def update
    respond_to do |format|
      if @developer.update(developer_params)
        format.html { redirect_to @developer, notice: 'Developer was successfully updated.' }
        format.json { render :show, status: :ok, location: @developer }
      else
        format.html { render :edit }
        format.json { render json: @developer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /developers/1
  # DELETE /developers/1.json
  def destroy
    @developer.destroy
    respond_to do |format|
      format.html { redirect_to developers_url, notice: 'Developer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_developer
      @developer = Developer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def developer_params
      params.require(:developer).permit(:name, :avatar)
    end
end

ep3/app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :set_developer, only: [:new, :update, :edit, :update]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit

  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :genre, :description, :release, :developer_id, :avatar)
    end

    def set_developer
      @developers = Developer.all
    end
end

ep3/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

ep3/app/helpers/application_helper.rb
module ApplicationHelper
end

ep3/app/helpers/control_users_helper.rb
module ControlUsersHelper
end

ep3/app/helpers/developers_helper.rb
module DevelopersHelper
end

ep3/app/helpers/games_helper.rb
module GamesHelper
end

ep3/app/helpers/welcome_helper.rb
module WelcomeHelper
end

ep3/app/views/control_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>email</th>
      <th>role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

ep3/app/views/developers/_form.html.erb
<%= form_for @developer, html: { multipart: true } do |f| %>

  <% if @developer.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@developer.errors.count, "error") %> prohibited this developer from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @developer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :avatar%><br>
    <%= f.file_field :avatar%>
  </div>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>



  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                developers_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

ep3/app/views/developers/edit.html.erb
<%- model_class = Developer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

ep3/app/views/developers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Developers</h1>

<table>
  <thead>
    <tr>
      <th>Avatar</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @developers.each do |developer| %>
      <tr>
        <td><%= image_tag developer.avatar.url(:thumb) %><td>
        <td><%= developer.name %></td>
        <td><%= link_to 'Show', developer %></td>
        <% if policy(@developers).index? %>
        <td><%= link_to 'Edit', edit_developer_path(developer) %></td>
        <td><%= link_to 'Destroy', developer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if policy(@developers).index? %>
<%= link_to 'New Developer', new_developer_path %>
<% end %>

ep3/app/views/developers/new.html.erb
<%- model_class = Developer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

ep3/app/views/developers/show.html.erb
<%- model_class = Developer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <%= image_tag @developer.avatar.url(:medium) %>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @developer.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              developers_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_developer_path(@developer), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              developer_path(@developer),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

ep3/app/views/games/_form.html.erb
<%= form_for @game, html: { multipart: true } do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :avatar %>
    <%= form.file_field :avatar %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :release %>
    <%= form.date_select :release %>
  </div>

  <div class="field">
    <%= form.label :developer_id %>
    <%= form.collection_select(:developer_id, @developers, :id, :name, prompt: true) %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

ep3/app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

ep3/app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Avatar</th>
      <th>Name</th>
      <th>Genre</th>
      <th>Description</th>
      <th>Release</th>
      <th>Developer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= image_tag game.avatar.url(:thumb) %><td>
        <td><%= game.name %></td>
        <td><%= game.genre %></td>
        <td><%= game.description %></td>
        <td><%= game.release %></td>
        <td><%= game.developer.name %></td>
        <td><%= link_to 'Show', game %></td>
        <% if policy(@games).index? %>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
      <% end %>
  </tbody>
</table>

<br>
<% if policy(@games).index? %>
<%= link_to 'New Game', new_game_path %>
<% end %>

ep3/app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

ep3/app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>

  <strong>Avatar:</strong>
  <%= image_tag @game.avatar.url(:medium) %>
  <hr>

  <strong>Name:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @game.genre %>
</p>

<p>
  <strong>Description:</strong>
  <%= @game.description %>
</p>

<p>
  <strong>Release:</strong>
  <%= @game.release %>
</p>

<p>
  <strong>Developer:</strong>
  <%= @game.developer.name %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

ep3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ep3" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"><%= link_to "Home", root_path %></a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <%else%>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
              <li><%= link_to "Sign In", user_session_path  %></li>
            <%end%>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

ep3/app/views/welcome/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Home</h1>


<ul>
  <li> <%= link_to "Developers", developers_path %></li>
  <li> <%= link_to "Games", games_path %></li>
  <li> <%= link_to "Users", control_users_index_path %></li>
</ul>